sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: jSUqziChWsNROEi8C2CfpetFuWd6JyQK+YXh5znSBIP9OcrCGWj1zHsQ7RnLMnZKI5L1dscPahpk/e9+Dl77r6I3QOeiHkuFJEN8IdATHsnVrsuwGGvBtgAwf6famqWmO1lRTOPtcDy1inLt8VnCV4XxccOMpIrjbjjGBIzZgdYPT+7oP+CYT4FKEw9LcuD6LANhG01FhKLNyaH8o4jfQpDk898IPKdcCT7sSyAUw8aLc5vRBymQ1sXrek3ZvvNi5/cs8GQVsVi323MuKZgQS6L5x3Qw2JHOlv8HUT/Vs+PDrbvBN7iOXOUwKdiE8fzIe6vC4TcRTslLgkNmWnR4TfWFcUEyWOUQnQ2odksy/0lXss1wHU8aAyMZ1pvFjBUVq8V9Vx1BWTb6qqOc2dZF8mhNezHoDDSpXTxRkd46dqCl17hn3JRnDZREvq0f4L6JM8jFiYd09AS2sXYEQbt/6BdtM2OZxmO3hH7qLwqLaSJ0Nb/A3S7ZPXSzYEPwkarrsQQ+uSIC0qjDFKPb/g7fmKEhLK2QFPS7T8axgXD7yIpJ1LPyz179kgwkmeJ3ZUkqHc+oFTfQS2KaBsj2xUloYwxJCAK/DdQlvGXRgzjjOgiceTaSDykA/TLoNyr7HcRWDdTPuirOaW3e/FiMZkq+yJWKmBJa3JZu+dnitn3ajaw=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Brewster-s-Millions_4709
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy